# Generated by Django 6.0.1 on 2026-01-30 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('matches_per_round', models.PositiveIntegerField(default=0)),
                ('bonus_defense_threshold', models.IntegerField(default=7)),
                ('match_weight', models.IntegerField(default=680)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kickoff_at', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure du match')),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(default=680)),
                ('phase', models.CharField(choices=[('POOL', 'Phase de poules'), ('R16', 'Huitièmes de finale'), ('QF', 'Quarts de finale / Barrages'), ('SF', 'Demi-finales'), ('FINAL', 'Finale')], default='POOL', max_length=10)),
                ('bonus_offense_home', models.BooleanField(default=False)),
                ('bonus_offense_away', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('date', models.DateField(blank=True, help_text='Date indicative de la journée', null=True)),
            ],
            options={
                'ordering': ['season', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score_pred', models.IntegerField()),
                ('away_score_pred', models.IntegerField()),
                ('bonus_home_pred', models.BooleanField(default=False)),
                ('bonus_away_pred', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.round'),
        ),
        migrations.CreateModel(
            name='DailyBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.round')),
            ],
        ),
        migrations.CreateModel(
            name='ScoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('delta', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('phase_multipliers', models.JSONField(default=dict)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competition')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='2025/2026', max_length=20)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='core.competition')),
            ],
            options={
                'ordering': ['competition', 'year'],
            },
        ),
        migrations.AddField(
            model_name='round',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='core.season'),
        ),
        migrations.CreateModel(
            name='SeasonScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Score saison',
                'verbose_name_plural': 'Scores saisons',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('competitions', models.ManyToManyField(blank=True, related_name='teams', to='core.competition')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='seasons', to='core.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='core.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='core.team'),
        ),
        migrations.CreateModel(
            name='CompetitionTeamPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('block_key', models.CharField(blank=True, max_length=50, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.PositiveSmallIntegerField(blank=True, help_text='Poule (Champions Cup)', null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_teams', to='core.competition')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_teams', to='core.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
            options={
                'ordering': ['pool', 'team__name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionRankingPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_try_scorer', models.CharField(blank=True, max_length=100)),
                ('best_kicker', models.CharField(blank=True, max_length=100)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.season')),
                ('winner_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_predictions', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionBonusPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_try_scorer', models.CharField(blank=True, default='', max_length=100)),
                ('best_point_scorer', models.CharField(blank=True, default='', max_length=100)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_winner', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamRankingPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('pool', models.PositiveSmallIntegerField(blank=True, help_text='Utilisé uniquement pour la Champions Cup', null=True)),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_rankings', to='core.competitionrankingprediction')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
            options={
                'ordering': ['pool', 'position'],
            },
        ),
        migrations.CreateModel(
            name='DailyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.round')),
            ],
            options={
                'verbose_name': 'Score journée',
                'verbose_name_plural': 'Scores journées',
                'unique_together': {('user', 'round')},
            },
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=('season', 'number'), name='unique_round_per_season'),
        ),
        migrations.AlterUniqueTogether(
            name='seasonscore',
            unique_together={('user', 'competition')},
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('competition', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='competitionteamprediction',
            unique_together={('player', 'competition', 'team')},
        ),
        migrations.AlterUniqueTogether(
            name='competitionteam',
            unique_together={('competition', 'season', 'team')},
        ),
        migrations.AlterUniqueTogether(
            name='competitionrankingprediction',
            unique_together={('player', 'season', 'competition')},
        ),
        migrations.AlterUniqueTogether(
            name='competitionbonusprediction',
            unique_together={('player', 'competition')},
        ),
        migrations.AlterUniqueTogether(
            name='teamrankingprediction',
            unique_together={('ranking', 'team')},
        ),
    ]
