# Generated by Django 6.0.1 on 2026-01-30 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRankingPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('pool', models.PositiveSmallIntegerField(blank=True, help_text='Utilisé uniquement pour la Champions Cup', null=True)),
            ],
            options={
                'ordering': ['pool', 'position'],
            },
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['season', 'number']},
        ),
        migrations.RemoveField(
            model_name='competition',
            name='season',
        ),
        migrations.RemoveField(
            model_name='match',
            name='bonus_defense_away',
        ),
        migrations.RemoveField(
            model_name='match',
            name='bonus_defense_home',
        ),
        migrations.RemoveField(
            model_name='round',
            name='competition',
        ),
        migrations.AddField(
            model_name='competition',
            name='matches_per_round',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='kickoff_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date et heure du match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='core.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='core.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='phase',
            field=models.CharField(choices=[('POOL', 'Phase de poules'), ('R16', 'Huitièmes de finale'), ('QF', 'Quarts de finale / Barrages'), ('SF', 'Demi-finales'), ('FINAL', 'Finale')], default='POOL', max_length=10),
        ),
        migrations.AlterField(
            model_name='round',
            name='date',
            field=models.DateField(blank=True, help_text='Date indicative de la journée', null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='CompetitionBonusPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_try_scorer', models.CharField(blank=True, default='', max_length=100)),
                ('best_point_scorer', models.CharField(blank=True, default='', max_length=100)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_winner', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionTeamPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('block_key', models.CharField(blank=True, max_length=50, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='2025/2026', max_length=20)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='core.competition')),
                ('teams', models.ManyToManyField(blank=True, related_name='seasons', to='core.team')),
            ],
            options={
                'ordering': ['competition', 'year'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.PositiveSmallIntegerField(blank=True, help_text='Poule (Champions Cup)', null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_teams', to='core.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_teams', to='core.season')),
            ],
            options={
                'ordering': ['pool', 'team__name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionRankingPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_try_scorer', models.CharField(blank=True, max_length=100)),
                ('best_kicker', models.CharField(blank=True, max_length=100)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
                ('winner_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_predictions', to='core.team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.season')),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='season',
            field=models.ForeignKey(default=0.9995064165844028, on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='core.season'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=('season', 'number'), name='unique_round_per_season'),
        ),
        migrations.AddField(
            model_name='teamrankingprediction',
            name='ranking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_rankings', to='core.competitionrankingprediction'),
        ),
        migrations.AddField(
            model_name='teamrankingprediction',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team'),
        ),
        migrations.AlterUniqueTogether(
            name='competitionbonusprediction',
            unique_together={('player', 'competition')},
        ),
        migrations.AlterUniqueTogether(
            name='competitionteamprediction',
            unique_together={('player', 'competition', 'team')},
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('competition', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='competitionteam',
            unique_together={('competition', 'season', 'team')},
        ),
        migrations.AlterUniqueTogether(
            name='competitionrankingprediction',
            unique_together={('player', 'season', 'competition')},
        ),
        migrations.AlterUniqueTogether(
            name='teamrankingprediction',
            unique_together={('ranking', 'team')},
        ),
    ]
