# Generated by Django 6.0.1 on 2026-01-18 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='journee',
        ),
        migrations.AlterUniqueTogether(
            name='pronostic',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pronostic',
            name='match',
        ),
        migrations.RemoveField(
            model_name='pronostic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='match',
            name='bonus_away',
        ),
        migrations.RemoveField(
            model_name='match',
            name='bonus_home',
        ),
        migrations.RemoveField(
            model_name='match',
            name='kickoff',
        ),
        migrations.RemoveField(
            model_name='match',
            name='score_away',
        ),
        migrations.RemoveField(
            model_name='match',
            name='score_home',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_away',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_home',
        ),
        migrations.AddField(
            model_name='competition',
            name='bonus_defense_threshold',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='competition',
            name='match_weight',
            field=models.IntegerField(default=680),
        ),
        migrations.AddField(
            model_name='match',
            name='away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='weight',
            field=models.IntegerField(default=680),
        ),
        migrations.CreateModel(
            name='CompetitionBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score_pred', models.IntegerField()),
                ('away_score_pred', models.IntegerField()),
                ('bonus_offense_pred', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competition')),
            ],
        ),
        migrations.CreateModel(
            name='DailyBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.round')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.round'),
        ),
        migrations.CreateModel(
            name='ScoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('delta', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competition')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='core.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='core.team'),
        ),
        migrations.DeleteModel(
            name='Journee',
        ),
        migrations.DeleteModel(
            name='Pronostic',
        ),
    ]
