# Generated by Django 6.0.1 on 2026-02-20 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonscore',
            name='points',
        ),
        migrations.AddField(
            model_name='seasonscore',
            name='match_points',
            field=models.IntegerField(default=0, verbose_name='Points Matchs'),
        ),
        migrations.AddField(
            model_name='seasonscore',
            name='ranking_points',
            field=models.IntegerField(default=0, verbose_name='Points Classement'),
        ),
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_best_try_scorer', models.CharField(blank=True, max_length=100)),
                ('real_best_point_scorer', models.CharField(blank=True, max_length=100)),
                ('rankings_json', models.JSONField(default=dict)),
                ('real_winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_winner', to='core.team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.season')),
            ],
        ),
    ]
