# Generated by Django 6.0.1 on 2026-02-20 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_seasonscore_points_seasonscore_match_points_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competitionbonusprediction',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='competitionteamprediction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='competitionbonusprediction',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.season'),
        ),
        migrations.AddField(
            model_name='competitionteamprediction',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.season'),
        ),
        migrations.AlterUniqueTogether(
            name='competitionbonusprediction',
            unique_together={('player', 'season', 'competition')},
        ),
        migrations.AlterUniqueTogether(
            name='competitionteamprediction',
            unique_together={('player', 'season', 'team')},
        ),
    ]
