# Generated by Django 6.0.1 on 2026-01-19 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_player_team_remove_match_journee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='phase',
            field=models.CharField(choices=[('POOL', 'Phase de poules'), ('R16', 'Huitièmes de finale'), ('QF', 'Quarts de finale'), ('SF', 'Demi-finales'), ('FINAL', 'Finale')], default='POOL', max_length=10),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='phase_multipliers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.match'),
        ),
        migrations.CreateModel(
            name='DailyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.round')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Score journée',
                'verbose_name_plural': 'Scores journées',
                'unique_together': {('user', 'round')},
            },
        ),
        migrations.CreateModel(
            name='SeasonScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Score saison',
                'verbose_name_plural': 'Scores saisons',
                'unique_together': {('user', 'competition')},
            },
        ),
    ]
