# Generated by Django 6.0.1 on 2026-02-20 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_competitionbonusprediction_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seasonscore',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='seasonscore',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.season'),
        ),
        migrations.AlterUniqueTogether(
            name='seasonscore',
            unique_together={('user', 'season', 'competition')},
        ),
    ]
