# Generated by Django 6.0.1 on 2026-02-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_seasonscore_unique_together_seasonscore_season_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailybonus',
            name='player',
        ),
        migrations.RemoveField(
            model_name='dailybonus',
            name='round',
        ),
        migrations.AlterModelOptions(
            name='teamrankingprediction',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='competitionrankingprediction',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teamrankingprediction',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='CompetitionBonus',
        ),
        migrations.DeleteModel(
            name='DailyBonus',
        ),
    ]
