# Generated by Django 6.0.1 on 2026-02-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_dailybonus_player_remove_dailybonus_round_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamrankingprediction',
            name='ranking',
        ),
        migrations.RemoveField(
            model_name='teamrankingprediction',
            name='team',
        ),
        migrations.DeleteModel(
            name='CompetitionRankingPrediction',
        ),
        migrations.DeleteModel(
            name='TeamRankingPrediction',
        ),
    ]
