# Generated by Django 6.0.1 on 2026-03-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seasonhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='name_override',
            field=models.CharField(blank=True, help_text="Nom personnalisé (ex: 'Match de barrage'). Laisse vide pour 'Journée X'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='phase',
            field=models.CharField(choices=[('POOL', 'Phase de poules'), ('R16', 'Huitièmes de finale'), ('QF', 'Quarts de finale / Barrages'), ('SF', 'Demi-finales'), ('FINAL', 'Finale')], default='POOL', max_length=10),
        ),
        migrations.AlterField(
            model_name='round',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='number',
            field=models.PositiveIntegerField(help_text='Ordre chronologique (1, 2, 3...)'),
        ),
    ]
