# Generated by Django 6.0.1 on 2026-04-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_round_name_override_round_phase_alter_round_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonscore',
            name='last_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
