# Generated by Django 6.0.1 on 2026-06-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_seasonscore_last_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonscore',
            name='podium_points',
            field=models.IntegerField(default=0, verbose_name='Points Podium'),
        ),
    ]
