# Generated by Django 6.0.6 on 2026-06-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seasonscore_podium_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['kickoff_at', 'id']},
        ),
        migrations.AddField(
            model_name='round',
            name='reminder_hours_sent',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
