# Generated by Django 6.0.6 on 2026-07-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_match_options_round_reminder_hours_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='scoring_config',
            field=models.JSONField(blank=True, null=True, verbose_name='Barème gelé'),
        ),
    ]
