# Generated by Django 6.0.6 on 2026-07-06 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_season_scoring_config'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoringConfig',
        ),
    ]
