# Generated by Django 6.0.6 on 2026-07-06 10:32

import json
from django.db import migrations, models


def convert_reminder_hours_to_json(apps, schema_editor):
    Round = apps.get_model('core', 'Round')
    for rnd in Round.objects.all():
        raw = rnd.reminder_hours_sent
        if isinstance(raw, str) and raw:
            rnd.reminder_hours_sent = json.dumps([h for h in raw.split(",") if h.strip()])
        elif isinstance(raw, str) and not raw:
            rnd.reminder_hours_sent = json.dumps([])
        rnd.save(update_fields=['reminder_hours_sent'])


def reverse_conversion(apps, schema_editor):
    Round = apps.get_model('core', 'Round')
    for rnd in Round.objects.all():
        try:
            data = json.loads(rnd.reminder_hours_sent)
            rnd.reminder_hours_sent = ",".join(str(h) for h in data) if data else ""
        except (ValueError, TypeError):
            rnd.reminder_hours_sent = ""
        rnd.save(update_fields=['reminder_hours_sent'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_scoringconfig'),
    ]

    operations = [
        migrations.RunPython(convert_reminder_hours_to_json, reverse_conversion),
        migrations.AlterField(
            model_name='round',
            name='reminder_hours_sent',
            field=models.JSONField(blank=True, default=list, verbose_name='Heures de rappel'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['match', 'player'], name='core_predic_match_i_78ab21_idx'),
        ),
    ]