# Generated by Django 6.0.6 on 2026-07-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_round_reminder_hours_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='seasons',
            field=models.ManyToManyField(blank=True, to='core.season'),
        ),
    ]
