# Generated by Django 6.0.6 on 2026-08-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_player_seasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='match_weight',
            field=models.IntegerField(default=800),
        ),
        migrations.AlterField(
            model_name='match',
            name='weight',
            field=models.IntegerField(default=800),
        ),
    ]
