# Generated by Django 6.0.6 on 2026-08-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_competition_match_weight_alter_match_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionresult',
            name='real_best_point_scorers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='real_best_try_scorers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
