# Generated by Django 6.0.6 on 2026-08-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_competitionresult_real_best_point_scorers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='aime',
            field=models.TextField(blank=True, default='', verbose_name="J'aime"),
        ),
        migrations.AddField(
            model_name='player',
            name='aime_pas',
            field=models.TextField(blank=True, default='', verbose_name="Je n'aime pas"),
        ),
        migrations.AddField(
            model_name='player',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
    ]
