# Generated by Django 6.0.6 on 2026-08-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_player_aime_player_aime_pas_player_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/', verbose_name='Photo de profil'),
        ),
    ]
