# Generated by Django 6.0.6 on 2026-08-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_player_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='alert_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email pour les alertes (H-24, H-6)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='aime',
            field=models.TextField(blank=True, default='', verbose_name='Club / équipes ou joueurs préférés'),
        ),
        migrations.AlterField(
            model_name='player',
            name='aime_pas',
            field=models.TextField(blank=True, default='', verbose_name='Clubs, équipes ou joueurs détestés'),
        ),
    ]
